import Head from 'next/head';
import Link from 'next/link';
import React, { useContext } from 'react';
import { languageContext } from '../../src/components/Contexts/Contexts';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Card } from 'react-bootstrap';
import { faArrowLeft, faLaptopCode } from '@fortawesome/free-solid-svg-icons'
import { motion } from "framer-motion"

const container = {
  hidden: { opacity: 1, scale: 0 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delayChildren: 1,
      staggerChildren: .6
    }
  }
}



export async function getServerSideProps(context) {
  const { id } = context.params
  const res = await fetch(`https://api.npoint.io/${id}`);
  const styleRes = await fetch('https://api.npoint.io/836be77be325d0a34bd8');
  const pageData = await res.json();
  const styles = await styleRes.json()

  return {
    props: {
      pageData,
      styles: styles,
    },
  }
}

export default function Home({ styles, pageData }) {
  const [language, setLanguage] = useContext(languageContext);
  const cardStyle = {
    backgroundColor: styles?.style?.["card-background-color"],
    color: styles?.style?.["card-text-color"],
    fontFamily: styles?.style?.["card-font"],
    width: '30vh',
    minWidth: '25vh',
    height: '40vh',
  }

  return (
    <>
      <Head>
        <title>Data Portrayal-Categories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href='/'>
        <p className="customButton d-flex justify-content-center align-items-center" variant="primary" style={{ position: 'fixed', right: '5vw', bottom: '15px', zIndex: 1, padding: '5px', paddingRight: '10px' }}>
          <FontAwesomeIcon icon={faArrowLeft} style={{ height: '12px', width: '25px' }} />
          <span style={{ color: 'black' }}>Return</span>
        </p>
      </Link>

      <div className="d-flex flex-wrap justify-content-center">
        {
          pageData?.cards?.map((data, idx) => (
            <motion.div key={idx} className=""
              variants={container}
              initial="hidden"
              animate="visible"
              whileHover={{ scale: 1.03 }}
            >
              <Card key={idx} style={cardStyle} className="m-2 text-center cardView">
                <Card.Img variant="top" src={data.photo} />
                <Card.Body className='d-flex align-items-center justify-content-center'>
                  <Card.Title style={{ fontSize: "2.4vh" }}>
                    <FontAwesomeIcon icon={faLaptopCode} style={{ height: "15px", width: "15px" }} />

                    {data[`title_${language}`]}

                    {language == 'en'
                      ? <p style={{ fontSize: "3vh" }}>{"$" + data.value_en}</p>
                      : <p style={{ fontSize: "3.2vh", paddingBottom: "5px" }}>{data.value_bn + "৳"}</p>}
                  </Card.Title>

                </Card.Body>
              </Card>
            </motion.div>
          ))
        }
      </div>
    </>
  )
}
