import Head from 'next/head'
import React, { useContext } from 'react';
import { landingPageDataContext } from '../src/components/Contexts/Contexts';


export const getStaticProps = async () => {
  let landingPageData;

  try {
    const res = await fetch('https://api.npoint.io/888cba28053234afdf51');
    landingPageData = await res.json();
  } catch (err) {
    console.log(err);
  }

  if (!landingPageData) {
    return {
      notFound: true,
    }
  }

  return {
    props: { landingPageData: landingPageData },
  }
}



export default function Home({ landingPageData }) {
  console.log(landingPageData);

  let [pageData, setPageData] = useContext(landingPageDataContext);
  setPageData(landingPageData);

  console.log(pageData);
  return (
    

      <div >
        <Head>
          <title>Data Portrayal</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

  )
}



// export const getStaticProps = async () => {
//   let styles;

//   try {
//     const res = await fetch('https://api.npoint.io/836be77be325d0a34bd8');
//     styles = await res.json();
//   } catch (err) {
//     console.log(err);
//   }

//   if (!styles) {
//     return {
//       notFound: true,
//     }
//   }

//   return {
//     props: { styles: styles },
//   }
// }