import Head from 'next/head'
import React, { useContext, useEffect, useState } from 'react';
import ComponentCard from '../src/components/ComponentCard/ComponentCard';
import { dataContext } from '../src/components/Contexts/Contexts';
import stylesContext from '../src/components/Contexts/Contexts'

export const getStaticProps = async () => {
  let landingPageData;

  const res = await fetch('https://api.npoint.io/888cba28053234afdf51');
  landingPageData = await res.json();


  if (!landingPageData) {
    return {
      notFound: true
    }
  }

  return {
    props: {
      landingPageData: landingPageData,
    },
  }
}

export default function Home({ landingPageData }) {

  const [pageData, setPageData] = useContext(dataContext);
  useEffect(() => {
    setPageData(landingPageData);
  }, [])

  return (


    <div >
      <Head>
        <title>Data Portrayal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>

  )
}
